name: Publish the Errsole MySQL package to npm

on:
  release:
    types: [created]
    branches:
      - master

jobs:
  test_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install

      # Run tests and generate coverage report
      - run: npm test -- --coverage
        continue-on-error: false

      # Send the coverage report to Coveralls
      - run: npm install coveralls --save-dev
      - run: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_MYSQL_TOKEN }}

      # Publish the package to npm
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
